### ISSUE TITLE
getting the "transaction underpriced" in the buy order method

### ISSUE THREAD

**Issue by wvrsn** [rarible/sdk#492]
I am trying to buy a nft using the rarible sdk, but I keep facing this error about "transaction underpriced", I already have tried to change the gas from the `Web3Ethereum` but even changing the gas I receive this error, do you what It could be?

```js
export const buy = async ({ contractAddress, tokenId }: { contractAddress: string, tokenId: string }) => {
	const privateKey = process.env["ETH_PRIVATE_KEY"] as string
	const rpcUrl = process.env["ETHEREUM_RPC_URL"] as string
	const itemId = `POLYGON:${contractAddress}:${tokenId}`

	// Setup a wallet using the private key
	const localKeyProvider = new HDWalletProvider({
		privateKeys: [
			privateKey
		],
		providerOrUrl: rpcUrl,
	});

	const web3 = new Web3(<any>localKeyProvider)
	const web3Ethereum = new Web3Ethereum({ web3 })
	const raribleSdk = createRaribleSdk(web3Ethereum, "prod")

	const order = (await raribleSdk.apis.item.getItemById({ itemId })).bestSellOrder
	if (order) {
		console.log("Sell order was found, purchasing...")
		const tx = await raribleSdk.order.buy.prepare({
			order
		})
		const response = await tx.submit({
			infiniteApproval: true,
			amount: 1,
		})

		console.log(response.hash)

		response.wait()

		console.log("The transaction was sent, waiting for a Rarible Protocol response...")
		console.log("Rarible Protocol response:", response)
	} else {
		console.warn(`Sell order was not found`)
	}
}

```
## Error
```
EthereumProviderError: transaction underpriced
    at Web3FunctionCall.<anonymous> (/Users/weverson/src/rarible-buy/node_modules/@rarible/web3-ethereum/build/index.js:256:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/weverson/src/rarible-buy/node_modules/tslib/tslib.js:115:69) {
  error: { code: -32000, message: 'transaction underpriced' },
```

**Comment by ex1st0r** [comment]
The "transaction underpriced" error occurs, when you're trying to send/replace a transaction and the gas price is too low.

**Comment by ex1st0r** [comment]
no, but you can use middleware for your provider and set gas price or base fee (for eip-1559) during sending transaction
