### ISSUE TITLE
ERROR Error: Unrecognized Seaport protocol

### ISSUE THREAD

**Issue by mostafa-rio** [rarible/sdk#498]
The error occurs on calling the buy method using fetched orders of an item

const tx = await sdk.order.buy({
    orderId: toOrderId("..."),
    amount: 1,
})

```
ERROR Error: Unrecognized Seaport protocol
    at getSeaportContract (seaport-utils.js:28:15)
    at seaport-utils.js:39:39
    at step (tslib.es6.js:102:1)
    at Object.next (tslib.es6.js:83:46)
    at tslib.es6.js:76:1
    at new ZoneAwarePromise (zone.js:1387:29)
    at Module.__awaiter (tslib.es6.js:72:1)
    at fulfillOrder (seaport-utils.js:34:20)
    at SeaportOrderHandler.<anonymous> (seaport.js:69:50)
    at step (tslib.es6.js:102:1)
```

**Comment by evgenynacu** [comment]
Hi @mostafa-rio 
What SDK version do you use?
I think this should be fixed in the newer SDK versions

There was an update to seaport and now it's supported by the SDK

**Comment by evgenynacu** [comment]
If this doesn't help, pls reopen the issue
