### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by MedNewton** [rarible/sdk#507]
Uncaught (in promise) Warning: Change network of your wallet. Config chainId=1, but wallet chainId=1
    at new Warning (http://localhost:3000/static/js/bundle.js:190282:24)
    at http://localhost:3000/static/js/bundle.js:201018:13
    at Generator.next (<anonymous>)
    at fulfilled (http://localhost:3000/static/js/bundle.js:691155:24)

**Comment by mostafa-rio** [comment]
check if your web3 provider and wallet is in sync and configured.
Which library are you using to connect ?

**Comment by ex1st0r** [comment]
Which connector/wallet do you use? Have you tried to update to latest version?
