### ISSUE TITLE
createKeccakHash is not a function

### ISSUE THREAD

**Issue by Digtyarenk0** [rarible/sdk#560]
**Describe the bug**
When creating an sdk instance I get an error inside `@rarible/protocol-ethereum-sdk/build/config/mainnet.js`

**Error**: 
```
keccak.ts:10 Uncaught (in promise) TypeError: createKeccakHash is not a function
    at keccak.ts:10:1
    at hash-utils.ts:7:1
    at keccak (hash.ts:19:1)
    at keccak256 (hash.ts:38:1)
    at id32 (id.js:11:1)
    at ./node_modules/@rarible/protocol-ethereum-sdk/build/config/mainnet.js (mainnet.js:29:1)
    at options.factory (react refresh:6:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
```

**What causes the error**: 
```
 const putEvmSDK = async () => {
    const sdk = createRaribleSdk(undefined, 'testnet'); // I get an error here
    console.log({ sdk });
  };
```

**To Reproduce**
Installed packages

Dependencies:
   ```
"@rarible/sdk": "0.13.57",
"react": "^18.2.0",
```

**Additional context**

- Babel version ``npm list @babel/core`` = 7.22
- npm v = 8.19.2
- node v =  v16.18.1

I also use react-app-rewired
And here are my webpack loaders
```
  const typescriptLoader = {
    test: [/\.ts?$/, /\.tsx?$/],
    loader: 'ts-loader',
    exclude: /node_modules/,
  };

  const babelLodaer = {
    test: /\.(js|jsx)$/,
    exclude: /node_modules/,
    use: {
      loader: 'babel-loader',
      options: {
        compact: true,
        presets: [
          '@babel/preset-flow',
          [
            '@babel/preset-env',
            {
              targets: {
                esmodules: true,
              },
            },
          ],
          '@babel/preset-modules',
          '@babel/preset-react',
          '@babel/preset-typescript',
        ],
        plugins: [
          'macros',
          '@babel/plugin-proposal-class-properties',
          '@babel/plugin-proposal-nullish-coalescing-operator',
          '@babel/plugin-syntax-dynamic-import',
          '@babel/plugin-proposal-private-methods',
          '@babel/plugin-proposal-private-property-in-object',
          '@babel/plugin-syntax-flow',
          isDev && require.resolve('react-refresh/babel'),
        ].filter(Boolean),
      },
    },
  };

  const laoders = [fileLoader, svgLoader, babelLodaer, typescriptLoader, cssLoader, resolveMJSLoader];
};

**Comment by evgenynacu** [comment]
@Digtyarenk0 it seems there is some problem with other dependencies
Could you probably attach yarn.lock?

**Comment by Digtyarenk0** [comment]
Here is my yarn.lock file
[yarn.txt](https://github.com/rarible/sdk/files/13348273/yarn.txt)

**Comment by evgenynacu** [comment]
@ex1st0r could you pls suggest what can go wrong here?

**Comment by ex1st0r** [comment]
Looks like you have some troubles with "keccak" package. 
Check existing and version of this package.

**Comment by Digtyarenk0** [comment]
"keccak" is not installed directly in the project (package.json)

**Comment by evgenynacu** [comment]
@ex1st0r keccak has 3.0.4 version installed
In one of my test project the same version is installed and everything's fine

Any other ideas?

**Comment by evgenynacu** [comment]
@Digtyarenk0 here's my yarn.lock from test project
Could you check also if you see any anomalies in your?
[yarn.txt](https://github.com/rarible/sdk/files/13365720/yarn.txt)

**Comment by Digtyarenk0** [comment]
I didn't notice any anomalies in your package. As you can see in the error, it comes from @rarible/protocol-ethereum-sdk and goes to ethereum-cryptography. Which is version 0.1.3. This ethereum-cryptography contains keccak version 3.0.0.
Here are the contents of the file
   **at keccak.ts:10:1**
   ````
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var hash_utils_1 = require("./hash-utils");
var createKeccakHash = require("keccak");
exports.keccak224 = hash_utils_1.createHashFunction(function () {
    return createKeccakHash("keccak224");
});
exports.keccak256 = hash_utils_1.createHashFunction(function () {
    return createKeccakHash("keccak256");
});
exports.keccak384 = hash_utils_1.createHashFunction(function () {
    return createKeccakHash("keccak384");
});
exports.keccak512 = hash_utils_1.createHashFunction(function () {
    return createKeccakHash("keccak512");
});
//# sourceMappingURL=keccak.js.map
````

As far as I understand, it imports keccak from the modules of my project, where keccak 3.0.4 is located.
Maybe the error is somehow related to the react-app-rewired config?

**Comment by vanya2h** [comment]
And what is resolve mjs loader that you use? Seems also like a cause

**Comment by Digtyarenk0** [comment]
I tried installing keccak directly and switching moduleResolution in the typescript config.
But the error persists
Here is the new config: 
```
const svgLoader = {
    test: /\.svg$/,
    issuer: /\.[jt]sx?$/,
    use: ['@svgr/webpack'],
  };

  const cssLoader = {
    test: /\.s[ac]ss$/i,
    use: [
      isDev ? 'style-loader' : MiniCssExtractPlugin.loader,
      'css-modules-typescript-loader',
      {
        loader: 'css-loader',
        options: {
          modules: {
            auto: /\.module\.scss$/i,
            localIdentName: isDev ? '[path][name]__[local]' : '[hash:base64:8]',
          },
        },
      },
      'sass-loader',
    ],
  };

  const fileLoader = {
    test: /\.(png|jpe?g|gif|woff2|woff)$/i,
    use: [
      {
        loader: 'file-loader',
      },
    ],
  };

  const babelLodaer = {
    test: /\.(js|jsx|tsx|ts)$/,
    exclude: /node_modules/,
    use: {
      loader: 'babel-loader',
      options: {
        compact: true,
        presets: [
          '@babel/preset-flow',
          [
            '@babel/preset-env',
            {
              targets: {
                esmodules: true,
              },
            },
          ],
          '@babel/preset-modules',
          ['@babel/preset-react', { runtime: 'automatic' }],
          '@babel/preset-typescript',
        ],
        plugins: [
          'macros',
          '@babel/plugin-proposal-class-properties',
          '@babel/plugin-proposal-nullish-coalescing-operator',
          '@babel/plugin-syntax-dynamic-import',
          '@babel/plugin-proposal-private-methods',
          '@babel/plugin-proposal-private-property-in-object',
          '@babel/plugin-syntax-flow',
          isDev && require.resolve('react-refresh/babel'),
        ].filter(Boolean),
      },
    },
  };

  const resolveMJSLoader = {
    test: /\.mjs/,
    include: /node_modules/,
    type: 'javascript/auto',
    resolve: {
      fullySpecified: false,
    },
  };

  const laoders = [fileLoader, svgLoader, babelLodaer, cssLoader, resolveMJSLoader];
```

**Comment by Digtyarenk0** [comment]
I also tried changing the config but it didn't work. Maybe there are some ideas?
Attached my config:
[config-overrides.txt](https://github.com/rarible/sdk/files/13482152/config-overrides.txt)
[devServer.txt](https://github.com/rarible/sdk/files/13482154/devServer.txt)
[fallback.txt](https://github.com/rarible/sdk/files/13482155/fallback.txt)
[loaders.txt](https://github.com/rarible/sdk/files/13482156/loaders.txt)
[plugins.txt](https://github.com/rarible/sdk/files/13482157/plugins.txt)
[resolvers.txt](https://github.com/rarible/sdk/files/13482158/resolvers.txt)
[tsconfig.txt](https://github.com/rarible/sdk/files/13482159/tsconfig.txt)

**Comment by evgenynacu** [comment]
@ex1st0r @vanya2h do you have any ideas?

**Comment by vanya2h** [comment]
@Digtyarenk0 one more idea:

1. Install keccak ^3.0.0 directly in your package.json
2. Create new file `keccak.js` with following content:
```
module.exports = require("keccak") 
// OR module.exports = require("keccak").default
```
3. Add to your buildResolvers new alias
```
alias: {
    "keccak": path.resolve(__dirname, "keccak.js"),
 },
```

Let's see how it's going to work..

**Comment by Digtyarenk0** [comment]
@vanya2h 
Installed in dependencies "keccak": "3.0.0",
I tried both the require("keccak") option and a couple of alias declaration options. But it did not help
```/* eslint-disable @typescript-eslint/no-var-requires */
const path = require('path');

const alias = require('react-app-rewire-alias');

module.exports = function buildResolvers(config, paths) {
  // Alias
  // alias.alias({
  //   'magic-sdk': path.resolve(__dirname, 'node_modules/magic-sdk/dist/cjs/index.js'),
  //   keccak: path.resolve(__dirname, 'keccak.js'),
  // })(config);

  return {
    ...config.resolve,
    extensions: ['.tsx', '.ts', '.js'],
    preferAbsolute: true,
    preferRelative: true,
    modules: [paths.src, 'node_modules'],
    mainFiles: ['index'],
    alias: {
      ...config.resolve.alias,
      keccak: path.resolve(__dirname, 'keccak.js'),
    },
  };
};
```

<img width="356" alt="image" src="https://github.com/rarible/sdk/assets/66130898/1dea35d6-bae9-4ef3-957a-ee7dc9d69c7f">

**Comment by Digtyarenk0** [comment]
Also, when installing dependencies yarn install, there are these warnings:

``` 
warning " > @rarible/api-client@0.16.4" has incorrect peer dependency "@rarible/types@>=0.10.0 <0.11.0".
warning "@rarible/sdk > @rarible/api-client@0.16.5-alpha.2" has incorrect peer dependency "@rarible/types@>=0.10.0 <0.11.0".
warning " > @rarible/sdk@0.13.61" has incorrect peer dependency "axios@^0.26.1".
warning "@rarible/sdk > @rarible/protocol-ethereum-sdk@0.13.61" has incorrect peer dependency "axios@^0.26.1".
warning "@rarible/sdk > @rarible/solana-sdk > @metaplex/js@4.12.0" has incorrect peer dependency "@metaplex-foundation/mpl-core@^0.0.2".
warning "@rarible/sdk > @rarible/solana-sdk > @metaplex/js@4.12.0" has incorrect peer dependency "@metaplex-foundation/mpl-token-metadata@^0.0.2".
warning "@rarible/sdk-wallet > @rarible/api-client@0.16.2-beta1" has incorrect peer dependency "@rarible/types@>=0.10.0 <0.11.0".
```

Why can't they influence?

**Comment by Digtyarenk0** [comment]
I rewrote the config from react-app-review to webpack and vite. I spent a lot of time and eventually found what was causing the error.
There was a `preferRelative` line in `config.resolve`

<img width="1062" alt="image" src="https://github.com/rarible/sdk/assets/66130898/82020a35-616d-4f11-8c14-d97f834a047b">
